/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiProcessRouteImport } from './routes/api/process'
import { Route as ApiHistoryRouteImport } from './routes/api/history'
import { Route as ApiApiKeysRouteImport } from './routes/api/api-keys'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as ApiHistoryEntryIdRouteImport } from './routes/api/history/$entryId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProcessRoute = ApiProcessRouteImport.update({
  id: '/api/process',
  path: '/api/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApiKeysRoute = ApiApiKeysRouteImport.update({
  id: '/api/api-keys',
  path: '/api/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiHistoryEntryIdRoute = ApiHistoryEntryIdRouteImport.update({
  id: '/$entryId',
  path: '/$entryId',
  getParentRoute: () => ApiHistoryRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/api/api-keys': typeof ApiApiKeysRoute
  '/api/history': typeof ApiHistoryRouteWithChildren
  '/api/process': typeof ApiProcessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/history/$entryId': typeof ApiHistoryEntryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/api/api-keys': typeof ApiApiKeysRoute
  '/api/history': typeof ApiHistoryRouteWithChildren
  '/api/process': typeof ApiProcessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/history/$entryId': typeof ApiHistoryEntryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/api/api-keys': typeof ApiApiKeysRoute
  '/api/history': typeof ApiHistoryRouteWithChildren
  '/api/process': typeof ApiProcessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/history/$entryId': typeof ApiHistoryEntryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/api/api-keys'
    | '/api/history'
    | '/api/process'
    | '/api/auth/$'
    | '/api/history/$entryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/api/api-keys'
    | '/api/history'
    | '/api/process'
    | '/api/auth/$'
    | '/api/history/$entryId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/dashboard'
    | '/api/api-keys'
    | '/api/history'
    | '/api/process'
    | '/api/auth/$'
    | '/api/history/$entryId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiApiKeysRoute: typeof ApiApiKeysRoute
  ApiHistoryRoute: typeof ApiHistoryRouteWithChildren
  ApiProcessRoute: typeof ApiProcessRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/process': {
      id: '/api/process'
      path: '/api/process'
      fullPath: '/api/process'
      preLoaderRoute: typeof ApiProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/api-keys': {
      id: '/api/api-keys'
      path: '/api/api-keys'
      fullPath: '/api/api-keys'
      preLoaderRoute: typeof ApiApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/history/$entryId': {
      id: '/api/history/$entryId'
      path: '/$entryId'
      fullPath: '/api/history/$entryId'
      preLoaderRoute: typeof ApiHistoryEntryIdRouteImport
      parentRoute: typeof ApiHistoryRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface ApiHistoryRouteChildren {
  ApiHistoryEntryIdRoute: typeof ApiHistoryEntryIdRoute
}

const ApiHistoryRouteChildren: ApiHistoryRouteChildren = {
  ApiHistoryEntryIdRoute: ApiHistoryEntryIdRoute,
}

const ApiHistoryRouteWithChildren = ApiHistoryRoute._addFileChildren(
  ApiHistoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiApiKeysRoute: ApiApiKeysRoute,
  ApiHistoryRoute: ApiHistoryRouteWithChildren,
  ApiProcessRoute: ApiProcessRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
